-- Tabla de Perfiles de Usuario
CREATE TABLE IF NOT EXISTS public.profiles (
    id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
    birth_date DATE,
    sign TEXT,
    plan TEXT DEFAULT 'normal',
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Tabla de Historial de Horóscopos
CREATE TABLE IF NOT EXISTS public.horoscopes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES auth.users ON DELETE CASCADE,
    date DATE DEFAULT CURRENT_DATE,
    sign TEXT,
    text TEXT,
    areas JSONB,
    actionable_advice TEXT,
    situations JSONB,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Habilitar Row Level Security (RLS)
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.horoscopes ENABLE ROW LEVEL SECURITY;

-- Políticas para Profiles
CREATE POLICY "Users can view their own profile" ON public.profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Users can update their own profile" ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Políticas para Horoscopes
CREATE POLICY "Users can view their own horoscopes" ON public.horoscopes FOR SELECT USING (auth.uid() = user_id);
CREATE POLICY "Users can insert their own horoscopes" ON public.horoscopes FOR INSERT WITH CHECK (auth.uid() = user_id);
